+incdir+../../rtl/ip/sketch_book
+incdir+../../rtl/ip/gru
../../rtl/ip/sketch_book/sketch_timing_800x600.sv
../../rtl/ip/sketch_book/sketch_frame_bram_bank.sv
../../rtl/ip/sketch_book/sketch_frame_ctrl.sv
../../rtl/ip/sketch_book/sketch_bram_writer.sv
../../rtl/ip/sketch_book/sketch_asset_rom.sv
../../rtl/ip/sketch_book/sketch_span_adapter.sv
../../rtl/ip/gru/engine_3d_lite/gru_lite_recip_area.sv
../../rtl/ip/gru/engine_3d_lite/gru_lite_triangle_setup.sv
../../rtl/ip/gru/engine_3d_lite/gru_lite_triangle_raster.sv
../../rtl/ip/sketch_book/sketch_triangle_lite_adapter.sv
../../rtl/ip/gru/gru_font_rom.sv
../../rtl/ip/sketch_book/sketch_gru_top.sv
../../rtl/ip/sketch_book/sketch_gdu_top.sv
../../rtl/ip/sketch_book/sketch_book_top.sv
../../rtl/ip/sketch_book/sketch_mmio_arbiter.sv
../../rtl/ip/scene_ctrl/scene_ctrl_math_pkg.sv
../../rtl/ip/scene_ctrl/scene_ctrl_model_fetcher.sv
../../rtl/ip/scene_ctrl/scene_ctrl_vertex_transform.sv
../../rtl/ip/scene_ctrl/scene_ctrl_triangle_frontend.sv
../../rtl/ip/scene_ctrl/scene_ctrl_painter_backend.sv
../../rtl/ip/scene_ctrl/scene_ctrl_model_cache.sv
../../rtl/ip/scene_ctrl/scene_ctrl_engine.sv
../../rtl/ip/scene_ctrl/scene_ctrl_pipeline.sv
../../rtl/ip/scene_ctrl/scene_ctrl_axi_regs.sv
../../rtl/ip/scene_ctrl/scene_ctrl_top.sv
../../rtl/ip/Bus_interconnects/axi2sram_sp_external.v
../../sim/sram.v
../../sim/agents/dvi_monitor_800x600.sv
../../sim/test/sketch/agent/sketch_ext_sram_agent.sv
../../sim/test/sketch/agent/sketch_cmd_monitor.sv
../../sim/test/sketch/3d/scene_sk/scene_sk_ui_abort_tb.sv
