#!/usr/bin/env python3
"""Convert triangulated Blender OBJ/MTL assets into SketchBook SK3D0 outputs."""
from __future__ import annotations

import argparse
from dataclasses import dataclass
import math
from pathlib import Path
import sys

from dynamic_surface_shading import annotate_dynamic_surface_shading
from color_rgb332 import hex_to_rgb332, rgb332_to_hex
from exporter_sk3d import encode_words, export_bin, export_mif, triangle_base_word_index
from importer_obj import ObjImportError, import_obj
from model import Model
from static_shading import apply_static_face_shading

# Leave a small margin below the positive endpoint so binary floating-point
# rounding cannot turn a fitted coordinate into 127.00000000000001.
SK3D_SAFE_COORDINATE = 127.0 - 1e-6


@dataclass(frozen=True)
class OutputTriplet:
    json_path: Path
    mif_path: Path
    bin_path: Path
    ref_path: Path


@dataclass(frozen=True)
class BuildOutputsResult:
    original: OutputTriplet
    shaded: OutputTriplet
    auto_fit_scale: float


def _fit_to_sk3d_coordinate_range(model: Model) -> float:
    """Uniformly shrink a normalised model when SK3D0 coordinates overflow."""
    maximum = max(abs(component) for vertex in model.vertices for component in vertex)
    if maximum <= SK3D_SAFE_COORDINATE:
        return 1.0

    scale = SK3D_SAFE_COORDINATE / maximum
    model.vertices = [
        (x * scale, y * scale, z * scale)
        for x, y, z in model.vertices
    ]
    return scale


def _asset_basename(output_path: Path) -> str:
    name = output_path.name
    if name.endswith(".s3d.mif"):
        return name[:-len(".s3d.mif")]
    return output_path.stem


def _normalise_model(model: Model, target_height: float, center: bool, scale_multiplier: float = 1.0) -> None:
    if target_height <= 0.0:
        raise ValueError("target height must be positive")
    if not math.isfinite(scale_multiplier) or scale_multiplier <= 0.0:
        raise ValueError("scale multiplier must be a finite positive number")
    if not model.vertices:
        raise ValueError("model has no vertices")

    min_y = min(vertex[1] for vertex in model.vertices)
    max_y = max(vertex[1] for vertex in model.vertices)
    source_height = max_y - min_y
    if source_height <= 0.0:
        raise ValueError("model height must be positive before scaling")

    scale = target_height / source_height * scale_multiplier
    scaled = [(vertex[0] * scale, vertex[1] * scale, vertex[2] * scale) for vertex in model.vertices]
    source_center = (0.0, 0.0, 0.0)
    if center:
        min_x = min(vertex[0] for vertex in scaled)
        max_x = max(vertex[0] for vertex in scaled)
        min_y = min(vertex[1] for vertex in scaled)
        max_y = max(vertex[1] for vertex in scaled)
        min_z = min(vertex[2] for vertex in scaled)
        max_z = max(vertex[2] for vertex in scaled)
        center_xyz = ((min_x + max_x) / 2.0, (min_y + max_y) / 2.0, (min_z + max_z) / 2.0)
        source_center = tuple(component / scale for component in center_xyz)
        scaled = [(x - center_xyz[0], y - center_xyz[1], z - center_xyz[2]) for x, y, z in scaled]

    model.vertices = scaled
    auto_fit_scale = _fit_to_sk3d_coordinate_range(model)
    # SK3D stores RGB332, so make the JSON reference asset use the exact same
    # palette rather than retaining pre-quantisation OBJ/MTL colours.
    for face in model.faces:
        face.color = rgb332_to_hex(hex_to_rgb332(face.color))
    model.origin = (0.0, 0.0, 0.0)
    model.metadata["normalization"] = {
        "target_height": target_height,
        "requested_scale": scale_multiplier,
        "effective_target_height": target_height * scale_multiplier * auto_fit_scale,
        "center": center,
        "source_height": source_height,
        "scale": scale,
        "sk3d_auto_fit_scale": auto_fit_scale,
        "source_center": list(source_center),
    }
    model.metadata["binary_format"] = "SK3D0"


def _write_ref_pkg(path: Path, asset_name: str, word_count: int, triangle_base: int) -> None:
    prefix = "".join(ch if ch.isalnum() else "_" for ch in asset_name).upper()
    text = (
        "// Generated by obj2sk3d.py\n"
        f"localparam int {prefix}_WORDS = {word_count};\n"
        f"localparam int {prefix}_TRI_BASE = {triangle_base};\n"
    )
    path.write_text(text, encoding="ascii", newline="\n")


def _write_asset_set(model: Model, asset_name: str, output_dir: Path) -> OutputTriplet:
    json_path = output_dir / f"{asset_name}.json"
    mif_path = output_dir / f"{asset_name}.s3d.mif"
    bin_path = output_dir / f"{asset_name}.s3d.bin"
    ref_path = output_dir / f"{asset_name}_ref_pkg.svh"
    words = encode_words(model)
    model.save(json_path)
    export_mif(model, mif_path)
    export_bin(model, bin_path)
    _write_ref_pkg(ref_path, asset_name, len(words), triangle_base_word_index(model))
    return OutputTriplet(json_path=json_path, mif_path=mif_path, bin_path=bin_path, ref_path=ref_path)


def build_outputs(
    obj_path: Path,
    mtl_path: Path,
    target_height: float,
    center: bool,
    output_path: Path,
    scale_multiplier: float = 1.0,
) -> BuildOutputsResult:
    imported = import_obj(obj_path, mtl_path)
    model = imported.model
    _normalise_model(model, target_height, center, scale_multiplier)
    normalization = model.metadata["normalization"]
    auto_fit_scale = float(normalization["sk3d_auto_fit_scale"])
    dynamic_model = annotate_dynamic_surface_shading(model)
    shaded_model = apply_static_face_shading(model)

    asset_name = _asset_basename(output_path)
    output_dir = output_path.parent

    output_dir.mkdir(parents=True, exist_ok=True)
    original = _write_asset_set(dynamic_model, asset_name, output_dir)
    shaded = _write_asset_set(shaded_model, f"{asset_name}_shade", output_dir)
    return BuildOutputsResult(original=original, shaded=shaded, auto_fit_scale=auto_fit_scale)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("obj", type=Path, help="triangulated OBJ exported from Blender")
    parser.add_argument("--mtl", type=Path, required=True, help="matching MTL file")
    parser.add_argument("--target-height", type=float, default=120.0, help="requested model height in scene units (auto-fitted to SK3D0 range if needed)")
    parser.add_argument("--scale", type=float, default=1.0,
                        help="uniform size multiplier applied after target-height normalisation")
    parser.add_argument("--center", action="store_true", help="recentre the scaled model around the bounding-box centre")
    parser.add_argument("--output", type=Path, required=True, help="output .s3d.mif path")
    args = parser.parse_args(argv)

    try:
        result = build_outputs(args.obj, args.mtl, args.target_height, args.center, args.output, args.scale)
    except (ObjImportError, ValueError) as exc:
        print(exc, file=sys.stderr)
        return 1

    if result.auto_fit_scale < 1.0:
        print(
            "Auto-fitted model to SK3D0 coordinate range "
            f"[-128, 127] (uniform scale {result.auto_fit_scale:.6g}; "
            f"effective height {args.target_height * args.scale * result.auto_fit_scale:.6g}).",
            file=sys.stderr,
        )

    for triplet in (result.original, result.shaded):
        print(f"Wrote {triplet.json_path}")
        print(f"Wrote {triplet.mif_path}")
        print(f"Wrote {triplet.bin_path}")
        print(f"Wrote {triplet.ref_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
